apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: test-clone-build-push
spec:
  params:
    - description: registry-domain/namespace where the output image should be pushed.
      name: image-registry-url
      type: string
  tasks:
    - name: clone-1
      params:
        - name: url
          value: git@github.com:rhdh-orchestrator-test/test-repo-j77jyk.git
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: test-shared-data
        - name: ssh-directory
          workspace: git-ssh-credentials
    - name: build-push-1
      params:
        - name: IMAGE
          value: $(params.image-registry-url)/test-repo-j77jyk
        - name: DOCKERFILE
          value: Dockerfile
        - name: CONTEXT
          value: .
      runAfter:
        - clone-1
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: test-shared-data
        - name: dockerconfig
          workspace: registry-credentials
  workspaces:
    - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
      name: test-shared-data
    - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
      name: registry-credentials
    - description: This workspace provides the credentials (ssh private key) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
      name: git-ssh-credentials
