
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: test-repo-j77jyk
    name: test-repo-j77jyk
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - image: quay.io/test/test-repo-j77jyk:latest
                  imagePullPolicy: Always
                  name: test-repo-j77jyk
                  ports:
                    - containerPort: 8080
                  resources: {}
            imagePullSecrets:
                - name: docker-credentials
            restartPolicy: Always
            securityContext: {}
status: {}

...
