apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: test-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  zzz_deprecatedclustername: ""
  managedfields: []
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: test-clone-push
    secrets:
      - name: test-image-registry
      - name: test-git-repo-github-com
  - apiVersion: v1
    data:
      known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSXdBQUFRRUFxMkE3aFJHbWRubTl0VURiTzlJRFN3Qks2VGJRYStQWFlQQ1B5NnJiVHJUdHc3UEhrY2NLcnBwMHlWaHA1SGRFSWNLcjZwTGxWREJmT0xYOVFVc3lDT1Ywd3pmaklKTmxHRVlzZGxMSml6SGhibjJtVWp2U0FIUXFaRVRZUDgxZUZ6TFFOblBIdDRFVlZVaDdWZkRFU1U4NEtlem1ENVFsV3BYTG12VTMxL3lNZitTZTh4aEhUdktTQ1pJRkltV3dvRzZtYlVvV2Y5bnpwSW9hU2pCK3dlcXFVVW1wYWFhc1hWYWw3MkorVVgyQisyUlBXM1JjVDBlT3pRZ3FsSkwzUktyVEp2ZHNqRTNKRUF2R3EzbEdIU1pYeTI4RzNza3VhMlNtVmkvdzR5Q0U2Z2JPRHFuVFdsZzcrd0M2MDR5ZEdYQThWSmlTNWFwNDNKWGlVRkZBYVE9PQ==
      ssh-privatekey: PFRPRE86IGluc2VydCB0aGUgcHJpdmF0ZSBzc2gga2V5IGZvciB5b3VyIGdpdCByZXBvPg==
    kind: Secret
    metadata:
      annotations:
        tekton.dev/git-0: github.com
      creationTimestamp: null
      name: test-git-repo-github-com
    type: kubernetes.io/ssh-auth
  - apiVersion: v1
    data:
      .dockerconfigjson: PFRPRE86IGluc2VydCB5b3VyIGRvY2tlciBjb25maWcganNvbj4=
    kind: Secret
    metadata:
      annotations:
        tekton.dev/docker-0: ""
      creationTimestamp: null
      name: test-image-registry
    type: kubernetes.io/dockerconfigjson
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: test-tekton-triggers-admin
    rules:
      - apiGroups:
          - triggers.tekton.dev
        resources:
          - eventlisteners
          - triggerbindings
          - triggertemplates
        verbs:
          - get
      - apiGroups:
          - tekton.dev
        resources:
          - pipelineruns
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      creationTimestamp: null
      name: test-clone-build-push
    spec:
      params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
      tasks:
        - name: clone-1
          params:
            - name: url
              value: git@github.com:rhdh-orchestrator-test/test-repo-j77jyk.git
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: test-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/test-repo-j77jyk
            - name: DOCKERFILE
              value: Dockerfile
            - name: CONTEXT
              value: .
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: test-shared-data
            - name: dockerconfig
              workspace: registry-credentials
      workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: test-shared-data
        - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
          name: registry-credentials
        - description: This workspace provides the credentials (ssh private key) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
          name: git-ssh-credentials
  - apiVersion: triggers.tekton.dev/v1beta1
    kind: TriggerBinding
    metadata:
      creationTimestamp: null
      name: test-git-event
    spec: {}
    status: {}
  - apiVersion: triggers.tekton.dev/v1beta1
    kind: EventListener
    metadata:
      creationTimestamp: null
      name: test-git-repo
    spec:
      namespaceSelector: {}
      resources: {}
      serviceAccountName: test-tekton-triggers-admin
      triggers:
        - bindings:
            - ref: test-git-event
          template:
            ref: test-run-clone-build-push
    status:
      configuration:
        generatedName: ""
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: test-git-repo
      name: test-git-repo
    spec:
      host: qe.lab.redhat.com
      path: /el-test-git-repo
      port:
        targetPort: port-8080
      tls:
        termination: passthrough
      to:
        kind: Service
        name: test-git-repo
        weight: 1
    status:
      ingress:
        - {}
  - apiVersion: triggers.tekton.dev/v1beta1
    kind: TriggerTemplate
    metadata:
      creationTimestamp: null
      name: test-run-clone-build-push
    spec:
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            creationTimestamp: null
            name: test-clone-build-push-$(uid)
          spec:
            params:
              - name: image-registry-url
                value: quay.io/test
            pipelineRef:
              name: test-clone-build-push
            serviceAccountName: test-clone-push
            workspaces:
              - name: test-shared-data
                volumeClaimTemplate:
                  metadata:
                    creationTimestamp: null
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
                    storageClassName: default
                  status: {}
              - name: git-ssh-credentials
                secret:
                  secretName: docker-credentials
              - name: git-basic-auth-credentials
                secret:
                  secretName: docker-credentials
              - name: registry-credentials
                secret:
                  secretName: docker-credentials
          status: {}
    status: {}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      creationTimestamp: null
      name: test-tekton-triggers-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: test-tekton-triggers-admin
    subjects:
      - kind: ServiceAccount
        name: test-tekton-triggers-admin
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      creationTimestamp: null
      name: test-tekton-triggers-admin
parameters: []
